### ISSUE TITLE
Build not triggered for PyTensor 2.11.3

### ISSUE THREAD

**Issue by ricardoV94** [conda-forge/pytensor-suite-feedstock#29]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

https://pypi.org/project/pytensor/

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

**Comment by maresb** [comment]
Given #31 it looks promising that this has been resolved.

**Comment by maresb** [comment]
Although it still seems unclear exactly what went wrong and why.
