### ISSUE TITLE
Please provide the osx-arm64 builds

### ISSUE THREAD

**Issue by ivaquero** [conda-forge/pytensor-suite-feedstock#5]
Since PyTensor is the new dependency of PyMC 5, osx-arm64 builds will allow macOS M1 users to update to the newest PyMC.

**Comment by ivaquero** [comment]
Thank you for your checking! I was also wondering why the migration was hindered.

**Comment by maresb** [comment]
I'm fairly stumped so I just [posted on Gitter](https://gitter.im/conda-forge/conda-forge.github.io?at=63998c158bdea01368b5ccf1).

**Comment by twiecki** [comment]
Is there anyone from the conda-forge team we can get some help from?
Maybe @ocefpaf has some idea?

**Comment by twiecki** [comment]
@wolfv @SylvainCorlay Sorry to tag you directly but this is a blocking issue for us we can't find out. It seems like the build process for ARM is stuck and won't restart, so we don't get ARM builds for PyTensor.

**Comment by maresb** [comment]
In particular it's the migrator, which is for some reason awaiting `mkl-service` which isn't actually an osx-arm dependency.

**Comment by ocefpaf** [comment]
I'll investigate this but if the only thing in the path for this migration is `mkl-service`, and that is not really needed, we can try to send a PR directly instead of waiting for the bot.

**Comment by twiecki** [comment]
@ocefpaf Seems like the bot didn't do its thing. Any idea?

**Comment by maresb** [comment]
> we can try to send a PR directly instead of waiting for the bot.

Attempting this in #7

**Comment by maresb** [comment]
Ah, right, pymc pins the older version. Could you make a new pymc release which pins v2.8.11?

**Comment by twiecki** [comment]
Just cut a new release.

**Comment by twiecki** [comment]
Successfully installed on osx-arm64, thanks everyone!
