### ISSUE TITLE
Rework BLAS config

### ISSUE THREAD

**Issue by maresb** [conda-forge/pytensor-suite-feedstock#52]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Figure out exactly what [this](https://discourse.pymc.io/t/performance-tip-if-youre-on-arm64-apples-m1-m2-chips-install-accelerate/12495/7) from @jonsedar is doing, and wrap it into this recipe.

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by jonsedar** [comment]
😅

**Comment by maresb** [comment]
I have some really sloppy instructions about how to test the conda-forge CI builds in https://github.com/conda-forge/pytensor-suite-feedstock/pull/38#issuecomment-1625950339 and subsequent.

To download the build from a CI run, go to the checks section of the PR run, click over to Azure Pipelines, and then look for "artifacts" and download the proper one for the platform.

(I should probably clean this up into a guide.)

**Comment by maresb** [comment]
Closed by #72. My understanding is that @jonsedar's stuff is not necessary when one instead uses `accelerate`.
