### ISSUE TITLE
Why is gxx required as run dependency?

### ISSUE THREAD

**Issue by RenaudLN** [conda-forge/pytensor-suite-feedstock#53]
### Comment:

Curious about the purpose of having a c++ compiler as a run dependency for pytensor?

I ran `build-locally.py` without the `gxx` dependency and it seemed to build OK, not sure if any pytensor features would be affected at runtime though.

**Comment by maresb** [comment]
It's used by the C backend, see `pytensor/link/c/cmodule.py`
