### ISSUE TITLE
Install accelerate when on OSX ARM64 chips

### ISSUE THREAD

**Issue by twiecki** [conda-forge/pytensor-suite-feedstock#55]
### Comment:

The accelerate blas implementation by Apple gives quite a nice speed-up and should be used instead of openblas for modern OSX installations (https://discourse.pymc.io/t/performance-tip-if-youre-on-arm64-apples-m1-m2-chips-install-accelerate/12495).

There is a conda-forge package available, so should be quite straight-forward.

**Comment by maresb** [comment]
Closed by #72
