### ISSUE TITLE
Remove pypy builds?

### ISSUE THREAD

**Issue by twiecki** [conda-forge/pytensor-suite-feedstock#60]
### Comment:

Started discussion in https://github.com/conda-forge/pytensor-suite-feedstock/pull/59.

pypy builds are often causing obscure build errors that are hard to track down. I'm not aware of anyone using pymc on pypy, and I'm also not sure if it actually even works given that we compile code. I also don't expect pypy to be able to run PyMC faster because of that (although pure python mode might actually do something, but we don't need binary builds for that).

**Comment by mattip** [comment]
Maybe someday you will be able to build the project using [HPy](https://hpyproject.org/), which would allow a single version to work for all python implementations and versions, and also be faster on PyPy. While the project recently released a new version, the work on a Cython backend and converting NumPy to use HPy is moving very slowly.

**Comment by maresb** [comment]
Hey @mattip, thanks for letting me know about HPy, it seems like a really cool project! Best of luck with that, it sounds like a really massive effort!

For now the PyPy builds are working again, and I'd like to keep it that way if possible. But honestly it can be a really big distraction when there's a failed build. I really want PyPy to succeed, so I'll do what I can within reasonable limits. Thanks for chiming in here.

**Comment by maresb** [comment]
I seemed to have solved the problem with the failed build in https://github.com/conda-forge/pytensor-suite-feedstock/pull/75.

Manual testing showed that we are not correctly detecting the C library, and we can follow that up in https://github.com/pymc-devs/pytensor/pull/662.
